server:
  host: "localhost"
  port: 8080
  timeout: 15
  idle_timeout: 30

database:
  username: "postgres"
  password: "password"
  host: "localhost"
  port: 5433
  dbname: "merchshop"

log:
  level: "info"

auth:
  secret_salt: "avitosec"